name: Build and Deploy to GKE with ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Install Just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with Google Artifact Registry
      run: just gcp-auth

    - name: Run full pipeline (build, test, push, and deploy)
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: ${{ secrets.GCP_REGION }}
        REPO_NAME: ${{ secrets.ARTIFACT_REPO }}
        ARGO_APP: ${{ secrets.ARGO_APP }}
      run: just pipeline
